version: '3.4'

services:
  eflmanagementapi:
    image: ${DOCKER_REGISTRY}/playground 

  eflmanagementdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrandompw
      MYSQL_USER: myrandomuser
      MYSQL_PASSWORD: myrandompw
    ports:
      - "3306:3306"
 