version: '3.4'

services:
  eflmanagementapi:
    build:
      context: .
      dockerfile: EFLManagementAPI/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44305
    ports:
      - "6687:80"
      - "44305:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  localtunnel:g
    image: devenda/sshtunnel:linux
  remotetunnel:
    image: devenda/sshtunnel:linux