version: '3.4'

services:
  eflmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44305
    ports:
      - "6687:80"
      - "44305:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  ssh-to-mysql:
    image: autosshimage
    build: ./sshTunnel
    container_name: autosshtomysql
    environment:
    - SSH_HOSTUSER=ecofablab
    - SSH_HOSTNAME=67.205.12.211 #chondu.dreamhost.com
    - SSH_TUNNEL_REMOTE=3306
    - SSH_TUNNEL_HOST=208.97.161.118 #mysql.ecofablab.be
    - SSH_TUNNEL_LOCAL=3306 #mysql.ecofablab.be mysql port
    - SSH_MODE=-Ng -L #Local forward mode (vs -R remote forward mode)
    - SSH_KEY_FILE=/ssh/id_rsa  
    restart: always
    volumes:
    - ./sshTunnel:/key #mount host current directory ./sshTunnel to container /key
    dns:
    - 8.8.8.8
    - 4.2.2.4