// <auto-generated />
using System;
using EFLManagementAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFLManagementAPI.Migrations
{
    [DbContext(typeof(EFLContext))]
    partial class EFLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFLManagementAPI.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardCode")
                        .IsRequired();

                    b.Property<DateTime>("TimestampRegistration");

                    b.Property<int>("UserId");

                    b.HasKey("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("EFLManagementAPI.Entities.Presence", b =>
                {
                    b.Property<int>("PresenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("TimestampScan");

                    b.Property<int>("UserId");

                    b.HasKey("PresenceId");

                    b.HasIndex("UserId");

                    b.ToTable("Presence");
                });

            modelBuilder.Entity("EFLManagementAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Comment");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Postcode");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<DateTime>("TimestampRegistration");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EFLManagementAPI.Entities.Card", b =>
                {
                    b.HasOne("EFLManagementAPI.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFLManagementAPI.Entities.Presence", b =>
                {
                    b.HasOne("EFLManagementAPI.Entities.User", "User")
                        .WithMany("Presence")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
